version: '3.0'

services:
  app:
    build: .
    container_name: numba_trading
    command: python main.py --port 80 --reload 
    restart: always
    ports:
      - 8080:80
    volumes:
      - .:/numba_trading